version: '3.8'

services:
  database:
    image: mysql:8.0.23
    container_name: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: database
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3307'
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ${project_path}:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ${project_path}:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database